version: '3.5'

services:

  sync_templates:
    build: ./
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    volumes:
      - ./:/home
    command: bash -c 'aws s3 sync . s3://${S3BUCKET}/${ENVIRONMENT}/ --exclude "*" --include "*.yml" --delete'

  base_infra_create:
    build: ./
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    volumes:
      - ./:/home
    command: bash -c 'aws cloudformation create-stack --stack-name ${BASE_INFRA_STACKNAME}-${ENVIRONMENT} --template-body file://master.yml --parameters file://${ENVIRONMENT}.json --capabilities  CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_IAM'

  base_infra_update:
    build: ./
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    volumes:
      - ./:/home
    command: bash -c 'aws cloudformation update-stack --stack-name ${BASE_INFRA_STACKNAME}-${ENVIRONMENT} --template-body file://master.yml --parameters file://${ENVIRONMENT}.json --capabilities  CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_IAM'
